# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{instrumental}
  s.version = "0.1.8"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Douglas F Shearer"]
  s.date = %q{2011-06-15}
  s.description = %q{Rails instrumentation and client for imperialapp.com}
  s.email = %q{support@imperialapp.com}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    ".gitignore",
    "Gemfile",
    "Gemfile.lock",
    "MIT-LICENCE",
    "README",
    "Rakefile",
    "VERSION",
    "init.rb",
    "instrumental.gemspec",
    "lib/instrumental.rb",
    "lib/instrumental/agent.rb",
    "lib/instrumental/configuration.rb",
    "lib/instrumental/intervalometer.rb",
    "lib/instrumental/railtie.rb",
    "lib/tasks/install.rake",
    "lib/tasks/milestone.rake",
    "lib/tasks/templates/instrumental.rb.erb",
    "spec/instrumental/agent_spec.rb",
    "spec/instrumental/configuration_spec.rb",
    "spec/instrumental/instrument_methods_spec.rb",
    "spec/instrumental/intervalometer_spec.rb",
    "spec/instrumental/setup_methods_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/imperialapp/instrumental}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{Rails instrumentation and client for imperialapp.com}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rake>, [">= 0"])
      s.add_runtime_dependency(%q<rspec>, [">= 0"])
      s.add_runtime_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

